### ISSUE TITLE
Allow a way to specify relative dates in .taskcluster.yml

### ISSUE THREAD

**Issue by Standard8** [taskcluster/taskcluster-github#64]
I found a snippet of older code from the templating engine that was used for specifying after how long artifacts would expire:

```
artifacts:
  'public':
    type: 'directory'
    path: '/home/worker/artifacts/public'
    expires: '{{#from_now }}7 days{{/from_now}}'
```

however, this fails with:

`Rejecting Schema: http://schemas.taskcluster.net/docker-worker/v1/payload.json#\nErrors:\n * data.artifacts['public'].expires should match format \"date-time\""`

Apparently some sort of similar functionality needs to be added to the github parser to allow this type of expiry to be specified (for now, I'm dropping the expires option).
